version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://splitmoney-api:3000
    container_name: splitmoney-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - splitmoney-network

networks:
  splitmoney-network:
    external: true
