version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_API_PUBLIC_URL: ${VITE_API_PUBLIC_URL}
    container_name: splitmoney-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - splitmoney-network

networks:
  splitmoney-network:
    external: true
